### ISSUE TITLE
RemovedInDjango110Warning for OptionParser usage in management command

### ISSUE THREAD

**Issue by Soviut** [peterbe/django-fancy-cache#28]
I'm using Django 1.9 and django-fancy-cache 0.8.0 and got the following warning when I called `manage.py fancy-urls` to check the stats.

```
/vagrant/env/local/lib/python2.7/site-packages/django/core/management/__init__.py:345: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  self.fetch_command(subcommand).run_from_argv(self.argv)
```

OptionParser is deprecated and should be using ArgumentParser instead.

**Comment by peterbe** [comment]
Are you interested in helping to write a patch? I'm sure you *are* interested but do you have the time and do you know how to run tests?

**Comment by Soviut** [comment]
I might be able to spare some time. The management command is certainly self-contained enough to contribute quickly.

**Comment by peterbe** [comment]
Excellent! I'll try to help as much as I can. But I'm too limited with time. But I care. Looking forward to some PRs :)

**Comment by YPCrumble** [comment]
@peterbe I think this could be closed - I'd be happy to write a PR if it's still an issue but I can't see anywhere we're using this deprecated call.
