### ISSUE TITLE
Does this work with CBVs?   All of the examples are old-style Django

### ISSUE THREAD

**Issue by ursomniac** [peterbe/django-fancy-cache#35]
(Question is in the title)

**Comment by peterbe** [comment]
I actually haven't tried. Please try and perhaps see if you can wrangle it to work and we can make a PR out of it. 
By the way, in my active Django 1.11 projects I still don't use class based views. I prefer regular view functions.

**Comment by pigmonkey** [comment]
I use django-fancy-cache with class base views by creating a mixin that wraps the dispatch function. I just use fancy cache for the querystring key feature, so my mixin is fairly simple, but you could expand it to do all the fancy key prefix stuff.

```
from django.conf import settings
from fancy_cache import cache_page


class CacheMixin(object):
    cache_timeout = settings.CACHE_TIMEOUT
    cache_querystring_keys = None

    def get_cache_timeout(self):
        return self.cache_timeout

    def get_cache_querystring_keys(self):
        return self.cache_querystring_keys

    def dispatch(self, *args, **kwargs):
        return cache_page(
            self.get_cache_timeout(),
            only_get_keys=self.get_cache_querystring_keys(),
        )(super(CacheMixin, self).dispatch)(*args, **kwargs)
```

**Comment by djw27** [comment]
You could also take the approach which the official docs suggest for `cache_page()`:

```
class MyView(View):
    @method_decorator(cache_page(CACHE_TIMEOUT))
    def get(self, request, *args, **kwargs):
        return super(MyView, self).get(request, *args, **kwargs)
```
