### ISSUE TITLE
Consider keeping blank querystring values

### ISSUE THREAD

**Issue by pigmonkey** [peterbe/django-fancy-cache#39]
I use django-fancy-cache for the `only_get_keys` functionality.

In one of my views I watch for the `pdf` querystring and return the page as a PDF if it is present. `/foo/bar/` returns the normal HTML web page, `/foo/bar/?pdf` returns the page as a PDF.

I have set `only_get_keys=['pdf']` for this view. However, I noticed that in normal usage (where `/foo/bar/` is generally hit first) Django returns the HTML page when visiting `/foo/bar/?pdf`.

This is caused by the use of [cgi.parse_qs](https://docs.python.org/2/library/cgi.html#cgi.parse_qs), which will not return empty values by default.

```
>>> import cgi
>>> cgi.parse_qs('pdf')
{}
>>> cgi.parse_qs('pdf=')
{}
>>> cgi.parse_qs('pdf=a')
{'pdf': ['a']}
```

For my use case, I would like to pass `keep_blank_values=True` to the parser.

```
>>> import cgi
>>> cgi.parse_qs('pdf', keep_blank_values=True)
{'pdf': ['']}
```

It appears that these blank values are [valid according to the RFC](https://tools.ietf.org/html/rfc3986#section-3.4).

For how django-fancy-cache uses the querystrings, I think it makes sense to use `keep_blank_values=True`. I would expect `/`, `/?pdf` and `/?pdf=foo` to all have different cache keys. However I admit that my use of `/?pdf` is sort of lazy, and I could just avoid this problem by watching for `?pdf=true` or something. I thought I would open an issue rather than submitting a pull request to see if there are any other opinions on the matter.

I'm happy to submit a pull request for this if people are ok with it.

**Comment by peterbe** [comment]
If you add `keep_blank_values=True` in a PR I'll merge it. It makes sense. I don't use django-fancy-cache much myself.

**Comment by peterbe** [comment]
By the way, check out [this blog post](https://www.peterbe.com/plog/json_response_cache_page_decorator) I wrote today about a "hybrid" solution where I avoid the Django `cache_page` decorator for my own for multiple good reasons. Perhaps write your own like that.
