### ISSUE TITLE
Add support for Django 3.1

### ISSUE THREAD

**Issue by macgeneral** [peterbe/django-fancy-cache#44]
First of all: thank you for this project - I hope it is still somewhat maintained.

According to the [Django documentation](https://www.djangoproject.com/download/#supported-versions) support for version 3.0 is dropped in one month (and 3.2 LTS should be released soon).

When I upgrade my Django application from v3.0.x to v3.1.x I get the following error when attempting to run the server:

```console
dev@vm:~$ python manage.py runserver

[..]

[..]/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 117, in _decorator
    middleware = middleware_class(view_func, *m_args, **m_kwargs)
TypeError: __init__() got multiple values for argument 'key_prefix'
```
which is coming from the @cache_page decorator:
```python
from fancy_cache import cache_page
from myproject.utils import cache

[..]

@cache_page(TTL, key_prefix=cache.cache_prefixer)
def my_view(...):
    [..]
```

It works as expected with Django <= 3.0.x.

**Comment by peterbe** [comment]
@macgeneral Would you mind attempting to set up a PR to fix it?
Start by adding `Django==3.0` and `Django==3.1` etc to https://github.com/peterbe/django-fancy-cache/blob/master/tox.ini and then work backwards to try to get the tests to pass in all versions of Django.

**Comment by macgeneral** [comment]
I will do so. I‘m just busy with work right now so I can probably start working on it in around one week.
