### ISSUE TITLE
Update django-fancy-cache on PyPI

### ISSUE THREAD

**Issue by danylev** [peterbe/django-fancy-cache#54]
Hi! First of all, thanks for your library!

I had a problem similar to - https://github.com/peterbe/django-fancy-cache/issues/44 and noticed that it already fixed with thanks to this PR https://github.com/peterbe/django-fancy-cache/pull/47/ 

But last release on PyPI was https://pypi.org/project/django-fancy-cache/#history on Novemver of 2019, so no recent changes to library to fix compatibility issue with Django 3.1+.

Can you please update it on PyPI?

**Comment by YPCrumble** [comment]
@peterbe this can now be closed.
